core/cart/urls.py
from django.urls import path, re_path
from . import views

app_name = "cart"

urlpatterns = [
    path("session/add-product", views.SessionAddProductView.as_view(), name="session-add-product"),
    path("session/remove-product", views.SessionRemoveProductView.as_view(), name="session-remove-product"),
    path("session/update-product-quantity", views.SessionUpdateProductQuantityView.as_view(), name="session-update-product-quantity"),
    path("summary", views.SessionCartSummaryView.as_view(), name="cart-summary"),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("website.urls")),
    path('dashboard/', include("dashboard.urls")),
    path('accounts/', include("accounts.urls")),
    path('shop/', include("shop.urls")),
    path('cart/', include("cart.urls")),
    path('order/', include("order.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

if settings.SHOW_DEBUGGER_TOOLBAR:
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls')),
                    ]

core/order/urls.py
from django.urls import path
from . import views

app_name = "order"

urlpatterns = [
    path("checkout/", views.OrderCheckoutView.as_view(), name="checkout"),
]

core/shop/urls.py
from django.urls import path, re_path
from . import views

app_name = "shop"

urlpatterns = [
    path("product/grid/", views.ShopProductGridView.as_view(), name="product_grid"),
    path("product/list/", views.ShopProductListView.as_view(), name="product-list"),
    re_path(r"product/(?P<slug>[-\w]+)/detail/", views.ShopProductDetailView.as_view(), name="product_detail"),

]

core/cart/models.py
from django.db import models

# Create your models here.
class CartModel(models.Model):
    user = models.ForeignKey("accounts.User", on_delete=models.CASCADE)
    
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.user.email
    
    
class CartItemModel(models.Model):
    cart = models.ForeignKey(CartModel, on_delete=models.CASCADE)
    product = models.ForeignKey("shop.ProductModel", on_delete=models.PROTECT)
    quantity = models.PositiveIntegerField(default=0)
    
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"{self.product.title} - {self.cart.id}"
    

core/cart/views.py
from django.shortcuts import render
from django.views.generic import View, TemplateView
from django.http import JsonResponse
from .cart import CartSession
# Create your views here.


class SessionAddProductView(View):
    
    def post(self, request, *args, **kwargs):
        cart = CartSession(request.session)
        product_id = request.POST.get("product_id")
        if product_id:
            cart.add_product(product_id)
        if request.user.is_authenticated:
            cart.merge_session_cart_in_db(request.user)
        return JsonResponse({"cart":cart.get_cart_dict(), "total_quantity":cart.get_total_quantity()})
    
class SessionUpdateProductQuantityView(View):

    def post(self, request, *args, **kwargs):
        cart = CartSession(request.session)
        product_id = request.POST.get("product_id")
        quantity = request.POST.get("quantity")
        if product_id and quantity:
            cart.update_product_quantity(product_id, quantity)
        if request.user.is_authenticated:
            cart.merge_session_cart_in_db(request.user)
        return JsonResponse({"cart": cart.get_cart_dict(), "total_quantity": cart.get_total_quantity()})


class SessionRemoveProductView(View):
    def post(self, request, *args, **kwargs):
        cart = CartSession(request.session)
        product_id = request.POST.get("product_id")
        if product_id:
            cart.remove_product(product_id)
        if request.user.is_authenticated:
            cart.merge_session_cart_in_db(request.user)
        return JsonResponse({"cart": cart.get_cart_dict(), "total_quantity": cart.get_total_quantity()})
    
class SessionCartSummaryView(TemplateView):
    template_name = "cart/cart-summary.html"
    
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        cart = CartSession(self.request.session)
        cart_items = cart.get_cart_items()
        context["cart_items"] = cart_items
        context['total_quantity'] = cart.get_total_quantity()
        context['total_payment_price'] = cart.get_total_payment_price()
        return context

core/templates/cart/cart-summary.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

    <!-- Content -->
    <div class="container content-space-1 content-space-lg-2">
      <div class="row">
        <div class="col-lg-8 mb-7 mb-lg-0">
          <!-- Heading -->
          <div class="d-flex justify-content-between align-items-end border-bottom pb-3 mb-7">
            <h1 class="h3 mb-0">سبد خرید</h1>
            <span>{{total_quantity}} مورد</span>
          </div>
          <!-- End Heading -->

          <!-- Form -->
          <form>
            <!-- List Group -->
            <ul class="list-group list-group-flush list-group-no-gutters mb-5">
            {% for item in cart_items %}
              <!-- Item -->
              <li class="list-group-item">
                <div class="d-flex">
                  <div class="flex-shrink-0">
                    <img class="avatar avatar-xl avatar-4x3" src="{{item.product_obj.image.url}}" alt="Image Description">
                  </div>

                  <div class="flex-grow-1 ms-3">
                    <div class="row">
                      <div class="col-sm-7 mb-3 mb-sm-0">
                        <h5><a class="text-dark" href="{% url 'shop:product_detail' slug=item.product_obj.slug %}">{{item.product_obj.title}}</a></h5>

                        <div class="d-block d-sm-none">
                          <h5 class="mb-1 formatted-price">{{item.total_price}}</h5>
                        </div>

                        <div class="d-grid gap-1">
                          <div class="text-body">
                            <span class="small">دسته بندی:</span>
                            <span class="fw-semibold small">{% for category in item.product_obj.category.all %}<a class="link-sm link-secondary" href="#">{{category.title}}</a>{% if not forloop.last %},{% endif %}{% endfor %}</span>
                          </div>
                        </div>

                        <div class="d-grid gap-1">
                          <div class="text-body">
                            <span class="small">قیمت هر واحد:</span>
                            <span class="fw-semibold small formatted-price">{{item.product_obj.get_price}}</span>
                          </div>
                        </div>
                      </div>
                      <!-- End Col -->

                      <div class="col-sm-3">
                        <div class="row">
                          <div class="col-auto">
                            <!-- Select -->
                            <select class="form-select form-select-sm mb-3" onchange="changeProductQuantity('{{ item.product_id }}', this.value)">
                              {% with ''|center:item.product_obj.stock as range %}
                              {% for _ in range %}
                              <option value="{{ forloop.counter }}" {% if forloop.counter == item.quantity %} selected {% endif %}>{{ forloop.counter }}</option>
                              {% endfor %}
                              {% endwith %}
                            </select>
                            <!-- End Select -->
                          </div>

                          <div class="col-auto">
                            <div class="d-grid gap-2 d-flex justify-content-between">
                              <button class=" btn btn-sm btn-icon text-danger border-0 mx-1" onclick="removeProduct('{{item.product_id}}')">
                                  <i class="bi-trash ms-1"></i> حذف
                              </button>
                              
                              <button class=" btn btn-sm btn-icon text-secondary border-0 mx-1" >
                                  <i class="bi-heart-fill ms-1 "></i> علایق
                              </button>
                          </div>
                          <!-- End Col -->
                        </div>
                        <!-- End Row -->
                      </div>
                      <!-- End Col -->

                      <div class="col-4 col-sm-2 d-none d-sm-inline-block text-right">
                        <span class="h5 d-block mb-1 formatted-price">{{item.total_price}}</span>
                      </div>
                      <!-- End Col -->
                    </div>
                    <!-- End Row -->
                  </div>
                </div>
              </li>
              <!-- End Item -->
            {% endfor %}

            </ul>
            <!-- End List Group -->

            <div class="d-sm-flex justify-content-end">
              <a class="link" href="{% url 'shop:product_grid' %}">
                به خرید ادامه دهید <i class="bi-chevron-left small ms-1"></i>
              </a>
            </div>
          </form>
          <!-- End Form -->
        </div>
        <!-- End Col -->

        <div class="col-lg-4">
          <div class="ps-lg-4">
            <!-- Card -->
            <div class="card card-sm shadow-sm mb-4">
              <div class="card-body">
                <div class="border-bottom pb-4 mb-4">
                  <h3 class="card-header-title">خلاصه هزینه</h3>
                </div>
                <form>

                  <div class="d-grid gap-3 mb-4">
                    <dl class="row">
                      <dt class="col-sm-6">مالیات</dt>
                      <dd class="col-sm-12 text-sm-end mb-0">به همراه 9% در هنگام پرداخت</dd>
                    </dl>
                    <!-- End Row -->

                    <dl class="row">
                      <dt class="col-sm-6">جمع</dt>
                      <dd class="col-sm-12 text-sm-end mb-0 formatted-price">{{total_payment_price}}</dd>
                    </dl>
                    <!-- End Row -->
                  </div>

                  <div class="d-grid">
                    <a class="btn btn-primary btn-lg" href="{% url 'order:checkout' %}">ثبت سفارش</a>
                  </div>
                </form>
              </div>
              <!-- End Card -->
            </div>

            <!-- Media -->
            <div class="d-flex align-items-center">
              <div class="flex-shrink-0">
                <div class="svg-icon svg-icon-sm text-primary">
                  <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" clip-rule="evenodd"
                      d="M22.1671 18.1421C22.4827 18.4577 23.0222 18.2331 23.0206 17.7868L23.0039 13.1053V5.52632C23.0039 4.13107 21.8729 3 20.4776 3H8.68815C7.2929 3 6.16183 4.13107 6.16183 5.52632V9H13C14.6568 9 16 10.3431 16 12V15.6316H19.6565L22.1671 18.1421Z"
                      fill="#035A4B" />
                    <path opacity="0.3" fill-rule="evenodd" clip-rule="evenodd"
                      d="M1.98508 18V13C1.98508 11.8954 2.88051 11 3.98508 11H11.9851C13.0896 11 13.9851 11.8954 13.9851 13V18C13.9851 19.1046 13.0896 20 11.9851 20H4.10081L2.85695 21.1905C2.53895 21.4949 2.01123 21.2695 2.01123 20.8293V18.3243C1.99402 18.2187 1.98508 18.1104 1.98508 18ZM5.99999 14.5C5.99999 14.2239 6.22385 14 6.49999 14H11.5C11.7761 14 12 14.2239 12 14.5C12 14.7761 11.7761 15 11.5 15H6.49999C6.22385 15 5.99999 14.7761 5.99999 14.5ZM9.49999 16C9.22385 16 8.99999 16.2239 8.99999 16.5C8.99999 16.7761 9.22385 17 9.49999 17H11.5C11.7761 17 12 16.7761 12 16.5C12 16.2239 11.7761 16 11.5 16H9.49999Z"
                      fill="#035A4B" />
                  </svg>

                </div>
              </div>
              <div class="flex-grow-1 ms-2">
                <span class="small me-1">نیاز به پشتیبانی دارید؟</span>
                <a class="link small" href="#">ارسال تیکت</a>
              </div>
            </div>
            <!-- End Media -->
          </div>
        </div>
        <!-- End Col -->
      </div>
      <!-- End Row -->
    </div>
    <!-- End Content -->

{% endblock %}

{% block extra_js %}
<script>
  function changeProductQuantity(product_id,quantity){
    $.ajax({
        url: "{%  url 'cart:session-update-product-quantity' %}",
        method: 'POST',
        data: {
            product_id: product_id,
            quantity: quantity,
            csrfmiddlewaretoken: '{{ csrf_token }}'

        },
        success: function (response) {
            console.log(response);
            window.location.reload();
            // do something with the response data
        },
        error: function (jqXHR, textStatus, errorThrown) {
            console.log(errorThrown);
            // handle the error case
        }
    });
}
  
function removeProduct(product_id){
    $.ajax({
        url: "{%  url 'cart:session-remove-product' %}",
        method: 'POST',
        data: {
            product_id: product_id,
            csrfmiddlewaretoken: '{{ csrf_token }}'

        },
        success: function (response) {
            console.log(response);
            window.location.reload();
            // do something with the response data
        },
        error: function (jqXHR, textStatus, errorThrown) {
            console.log(errorThrown);
            // handle the error case
        }
    });
}
</script>
{% endblock extra_js %}