core/cart/urls.py
from django.urls import path, re_path
from . import views

app_name = "cart"

urlpatterns = [
    path("session/add-product", views.SessionAddProductView.as_view(), name="session-add-product"),
    path("session/remove-product", views.SessionRemoveProductView.as_view(), name="session-remove-product"),
    path("session/update-product-quantity", views.SessionUpdateProductQuantityView.as_view(), name="session-update-product-quantity"),
    path("summary", views.SessionCartSummaryView.as_view(), name="cart-summary"),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("website.urls")),
    path('dashboard/', include("dashboard.urls")),
    path('accounts/', include("accounts.urls")),
    path('shop/', include("shop.urls")),
    path('cart/', include("cart.urls")),
    path('order/', include("order.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

if settings.SHOW_DEBUGGER_TOOLBAR:
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls')),
                    ]

core/shop/urls.py
from django.urls import path, re_path
from . import views

app_name = "shop"

urlpatterns = [
    path("product/grid/", views.ShopProductGridView.as_view(), name="product_grid"),
    path("product/list/", views.ShopProductListView.as_view(), name="product-list"),
    re_path(r"product/(?P<slug>[-\w]+)/detail/", views.ShopProductDetailView.as_view(), name="product_detail"),

]

core/shop/models.py
from django.db import models
from decimal import Decimal
from django.core.validators import MaxValueValidator, MinValueValidator
from ckeditor.fields import RichTextField
# Create your models here.


class ProductStatusType(models.IntegerChoices):
    publish = 1, ("نمایش")
    draft = 2, ("عدم نمایش")


class ProductCategoryModel(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(allow_unicode=True, unique=True)
    
    
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    
    
    def  __str__(self):
        return self.title


class ProductModel(models.Model):
    user = models.ForeignKey("accounts.User", on_delete=models.PROTECT)
    category = models.ManyToManyField(ProductCategoryModel)
    title = models.CharField(max_length=255)
    slug = models.SlugField(allow_unicode=True, unique=True)
    image = models.ImageField(default="/default/product-image.png",upload_to="product/img/")
    description = RichTextField()
    brief_description = models.TextField(null=True, blank=True)
    stock = models.PositiveIntegerField(default=0)
    status = models.IntegerField(choices=ProductStatusType.choices, default=ProductStatusType.draft.value)
    price = models.DecimalField(max_digits=10, decimal_places=0)
    discount_percent = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(100)])
    
    
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ["-created_date"]
        
        
    def get_price(self):
        discount_amount = self.price * Decimal(self.discount_percent / 100)
        discounted_amount = self.price - discount_amount
        
        return int(discounted_amount)
    
    
    def get_show_price(self):
        discount_amount = self.price * Decimal(self.discount_percent / 100)
        discounted_amount = self.price - discount_amount
        
        return "{:,}".format(int(discounted_amount))
    
    def get_show_raw_price(self):
        return "{:,}".format(self.price)
    
    def is_discounted(self):
        return self.discount_percent != 0
    
    def is_published(self):
        return self.status == ProductStatusType.publish.value
    
    def get_images(self):
        return self.images.all()
    
    def __str__(self) -> str:
        return self.title
    
class ProductImageModel(models.Model):
    product = models.ForeignKey(ProductModel,on_delete=models.CASCADE,related_name="product_images")
    file = models.ImageField(upload_to="product/extra-img/")
    
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ["-created_date"]

core/dashboard/admin/forms/products.py
from django import forms
from shop.models import ProductModel, ProductImageModel



class ProductImageForm(forms.ModelForm):
    # adding additional images to a product
    class Meta:
        model = ProductImageModel
        fields = [
            "file",
        ]
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['file'].widget.attrs['class'] = 'form-control'
        self.fields['file'].widget.attrs['accept'] = 'image/png, image/jpg, image/jpeg'


class ProductEdit(forms.ModelForm):
    class Meta:
        model = ProductModel
        fields = [
            "category",
            "title",
            "slug",
            "image",
            "description",
            "brief_description",
            "stock",
            "status",
            "price",
            "discount_percent",
        ]
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['category'].widget.attrs['class'] = "form-control"
        self.fields['title'].widget.attrs['class'] = "form-control"
        self.fields['slug'].widget.attrs['class'] = "form-control"
        self.fields['image'].widget.attrs['class'] = "form-control"
        self.fields['description'].widget.attrs['class'] = "form-control"
        self.fields['brief_description'].widget.attrs['class'] = "form-control"
        self.fields['stock'].widget.attrs['class'] = "form-control"
        self.fields['stock'].widget.attrs['type'] = "number"
        self.fields['status'].widget.attrs['class'] = "form-select"
        self.fields['price'].widget.attrs['class'] = "form-control"
        self.fields['discount_percent'].widget.attrs['class'] = "form-control"
        
        
        

core/dashboard/admin/views/products.py
from django.shortcuts import redirect
from django.views.generic import (
    UpdateView,
    ListView,
    DeleteView,
    CreateView)
from django.contrib.auth.mixins import LoginRequiredMixin
from dashboard.permissions import HasAdminAccessPermission
from django.contrib.auth import views as auth_views
from dashboard.admin.forms import AdminPasswordChangeForm, ProductEdit, ProductImageForm
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from shop.models import ProductModel, ProductCategoryModel, ProductImageModel
from django.contrib import messages
# Create your views here.


class AdminDashboardSecurityEditView(LoginRequiredMixin, HasAdminAccessPermission, SuccessMessageMixin, auth_views.PasswordChangeView):
    template_name = 'dashboard/admin/profile/security-edit.html'
    form_class = AdminPasswordChangeForm
    success_url = reverse_lazy("dashboard:admin:security-edit")
    success_message = "رمز عبور با موفقیت بروزرسانی شد"
    
    
class AdminProductListView(LoginRequiredMixin, HasAdminAccessPermission, ListView):
    template_name = "dashboard/admin/products/product-list.html"
    
    
    paginate_by = 10
    
    def get_paginate_by(self, queryset):
        return self.request.GET.get('page_size', self.paginate_by)
    
    def get_queryset(self):
        queryset = ProductModel.objects.all()
        if search_q:=self.request.GET.get('q'):
            queryset = queryset.filter(title__icontains=search_q)  
        if category_id:=self.request.GET.get('category_id'):
            queryset = queryset.filter(category__id=category_id)
        if min_price:=self.request.GET.get('min_price'):
            queryset = queryset.filter(price__gte=min_price)
        if max_price:=self.request.GET.get('max_price'):
            queryset = queryset.filter(price__lte=max_price)
        if max_price:=self.request.GET.get('max_price'):
            queryset = queryset.filter(price__lte=max_price)
        if order_by:=self.request.GET.get('order_by'):
            queryset = queryset.order_by(order_by)
            
        return queryset
    
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        
        context["total_amount"] = self.get_queryset().count()
        context["categories"] = ProductCategoryModel.objects.all()
        return context
    
class AdminProductCreateView(LoginRequiredMixin, HasAdminAccessPermission, SuccessMessageMixin, CreateView):
    template_name = "dashboard/admin/products/product-create.html"
    queryset = ProductModel.objects.all()
    form_class = ProductEdit
    success_message = "ایجاد محصول با موفقیت انجام شد"
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        super().form_valid(form)
        return redirect(reverse_lazy("dashboard:admin:product-edit", kwargs={"pk":form.instance.pk}))
    
    def get_success_url(self):
        return reverse_lazy("dashboard:admin:product-list")

class AdminProductEditView(LoginRequiredMixin, HasAdminAccessPermission, SuccessMessageMixin, UpdateView):
    template_name = "dashboard/admin/products/product-edit.html"
    queryset = ProductModel.objects.all()
    form_class = ProductEdit
    success_message = "ویرایش محصول با موفقیت انجام شد"
    def get_success_url(self):
        return reverse_lazy("dashboard:admin:product-edit", kwargs={"pk":self.get_object().pk})
    
    
class AdminProductDeleteView(LoginRequiredMixin, HasAdminAccessPermission, SuccessMessageMixin, DeleteView):
    template_name = "dashboard/admin/products/product-delete.html"
    queryset = ProductModel.objects.all()
    success_message = "محصول مورد نظر با موفقیت حذف شد"
    success_url = reverse_lazy("dashboard:admin:product-list")
    


class AdminProductAddImageView(LoginRequiredMixin, HasAdminAccessPermission, CreateView):
    http_method_names = ['post']
    form_class = ProductImageForm

    def get_success_url(self):
        return reverse_lazy('dashboard:admin:product-edit', kwargs={'pk': self.kwargs.get('pk')})

    def form_valid(self, form):
        product_id = self.kwargs.get('pk')
        try:
            product = ProductModel.objects.get(pk=product_id)
            form.instance.product = product
            form.save()  # Explicitly save the form
            messages.success(self.request, 'تصویر مورد نظر با موفقیت ثبت شد')
            return redirect(self.get_success_url())
        except ProductModel.DoesNotExist:
            messages.error(self.request, 'محصول مورد نظر یافت نشد')
            return redirect(self.get_success_url())


class AdminProductRemoveImageView(LoginRequiredMixin, HasAdminAccessPermission, SuccessMessageMixin, DeleteView):
    http_method_names = ["post"]
    success_message = "تصویر مورد نظر با موفقیت حذف شد"

    def get_queryset(self):
        return ProductImageModel.objects.filter(product__id=self.kwargs.get('pk'))
    
    def get_object(self, queryset=None):
        return self.get_queryset().get(pk=self.kwargs.get('image_id'))

    def get_success_url(self):
        return reverse_lazy('dashboard:admin:product-edit', kwargs={'pk': self.kwargs.get('pk')})

    def form_invalid(self, form):
        messages.error(
            self.request, 'اشکالی در حذف تصویر رخ داد لطفا مجدد امتحان نمایید')
        return redirect(reverse_lazy('dashboard:admin:product-edit', kwargs={'pk': self.kwargs.get('pk')}))

core/templates/dashboard/admin/products/product-create.html
{% extends 'dashboard/admin/base.html' %}
{% load static %}

{% block breadcrumb %}
        
    
                <!-- Breadcrumb -->
                <nav aria-label="breadcrumb">
                  <ol class="breadcrumb breadcrumb-light mb-0">
                    <li class="breadcrumb-item">حساب</li>
                    <li class="breadcrumb-item">داشبورد ادمین</li>
                    <li class="breadcrumb-item active" aria-current="page">
                      ایجاد محصول
                    </li>
                  </ol>
                </nav>
                <!-- End Breadcrumb -->
              </div>
              <!-- End Col -->
    
              
{% endblock %}
{% block content %}
<!-- Card -->
<div class="card">
    <div class="card">
        <!-- Header -->
        <div class="card-header border-bottom">
          <h5 class="card-header-title">ایجاد محصول</h5>
        </div>
        <!-- End Header -->

        <!-- Body -->
        <form action="." method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="card-body">
            <div class="row d-flex ">
              <div class="col-md-6 mb-3">
                <label for="id_title">نام محصول</label>
                {{form.title}}
              </div>
              <div class="col-md-6 mb-3">
                <label for="id_slug">slug محصول</label>
                {{form.slug}}
              </div>
              <div class="col-md-6 mb-3">
                <label >تعداد</label>
                {{form.stock}}
              </div>

              <div class="col-md-6 mb-3">
                <label >وضعیت</label>
                {{form.status}}
              </div>
              <div class="col-md-6 mb-3">
                <label >دسته بندی</label>
                {{form.category}}
              </div>
              <div class="col-md-4 mb-3">
                <label >قیمت</label>
                {{form.price}}
              </div>
              <div class="col-md-2 mb-3">
                <label >درصد تخفیف</label>
                {{form.discount_percent}}
              </div>

              <div class="col-md-12 mb-3">
                <label >توضیحات کوتاه</label>
                {{form.brief_description}}
              </div>

              <div class="col-md-12 mb-3">
                <label >توضیحات</label>
                {{form.description}}
              </div>

              <div class="col-md-12 mb-3">
                <label>تصویر محصول</label>
                <!-- File input for image -->
                {{ form.image }}
            
                <!-- Image preview -->
                <div id="imagePreviewContainer" class="mt-2" style="display:none; max-width: 300px; max-height: 300px; overflow: hidden;">
                    <img id="imagePreview" src="" alt="Image Preview" style="width: 100%; height: auto;">
                </div>
            </div>

            </div>
        </div>
        <div class="card-footer">
            <div class=" d-flex pt-5 justify-content-end">
                <a class="btn btn-secondary ms-3" href="{% url 'dashboard:admin:product-list' %}">بازگشت</a>
                <button type="submit" class="btn btn-primary ms-3">ایجاد</button>
            </div>
        </form>
      </div>
{% endblock %}

{% block extra_js %}
<script>
    document.addEventListener('DOMContentLoaded', function() {
        // Get the title and slug input elements
        const titleInput = document.getElementById('id_title');
        const slugInput = document.getElementById('id_slug');

        // Function to slugify the title input, supporting Persian characters
        function slugify(text) {
            // Normalize to remove accents and convert to lowercase
            let slugified = text
                .toString()
                .normalize('NFD')  // Normalize to remove diacritical marks (accents)
                .toLowerCase()     // Convert to lowercase
                .replace(/[^a-z0-9\s\u0600-\u06FF\-]/g, '')  // Allow Persian chars (Unicode range for Persian: \u0600-\u06FF)
                .replace(/\s+/g, '-')    // Replace spaces with hyphens
                .replace(/-+/g, '-');    // Replace multiple hyphens with one

            // Return the slug directly (without URL encoding)
            return slugified;
        }

        // Add an event listener to the title input
        titleInput.addEventListener('input', function() {
            // Update the slug field with the slugified version of the title
            slugInput.value = slugify(titleInput.value);
        });
    });

    document.getElementById('id_image').addEventListener('change', function(event) {
        var reader = new FileReader();
        var file = event.target.files[0];

        if (file) {
            // When a file is selected, show the preview
            reader.onload = function(e) {
                var imagePreview = document.getElementById('imagePreview');
                var imagePreviewContainer = document.getElementById('imagePreviewContainer');
                
                // Set the src attribute of the img tag to the file data
                imagePreview.src = e.target.result;

                // Show the preview container
                imagePreviewContainer.style.display = 'block';
            };

            // Read the file as a data URL
            reader.readAsDataURL(file);
        }
    });

</script>
{% endblock extra_js %}

core/templates/dashboard/admin/products/product-delete.html
{% extends 'dashboard/admin/base.html' %}
{% load static %}

{% block breadcrumb %}
        
    
                <!-- Breadcrumb -->
                <nav aria-label="breadcrumb">
                  <ol class="breadcrumb breadcrumb-light mb-0">
                    <li class="breadcrumb-item">حساب</li>
                    <li class="breadcrumb-item">داشبورد ادمین</li>
                    <li class="breadcrumb-item active" aria-current="page">
                      ویرایش محصول
                    </li>
                  </ol>
                </nav>
                <!-- End Breadcrumb -->
              </div>
              <!-- End Col -->
    
              
{% endblock %}
{% block content %}
<!-- Card -->
<div class="card">
    <div class="card">
        <!-- Header -->
        <div class="card-header border-bottom">
          <h5 class="card-header-title">ویرایش/ساخت محصول</h5>
        </div>
        <!-- End Header -->

        <!-- Body -->
        <form action="." method="post">
        {% csrf_token %}
        <div class="card-body">
            <div class="row d-flex">
                <p>آیا از حذف این محصول اطمینان دارید؟</p>
                <p>نام محصول: {{object.title}}</p>
                <p>شناسه محصول: {{object.pk}}</p>
            </div>
    
        </div>
        <div class="card-footer">
            <div class=" d-flex pt-5 justify-content-end">
                <a class="btn btn-secondary ms-3" href="{% url 'dashboard:admin:product-edit' pk=object.pk %}">بازگشت</a>
                <button type="submit" class="btn btn-danger ms-3">حذف</button>
            </div>
        </form>
      </div>
{% endblock %}

core/templates/dashboard/admin/products/product-edit.html
{% extends 'dashboard/admin/base.html' %}
{% load static %}

{% block breadcrumb %}
        
    
                <!-- Breadcrumb -->
                <nav aria-label="breadcrumb">
                  <ol class="breadcrumb breadcrumb-light mb-0">
                    <li class="breadcrumb-item">حساب</li>
                    <li class="breadcrumb-item">داشبورد ادمین</li>
                    <li class="breadcrumb-item active" aria-current="page">
                      ویرایش محصول
                    </li>
                  </ol>
                </nav>
                <!-- End Breadcrumb -->
              </div>
              <!-- End Col -->
    
              
{% endblock %}
{% block content %}
<!-- Card -->
<div class="card">
    <div class="card">
        <!-- Header -->
        <div class="card-header border-bottom d-flex justify-content-between items-align-center">
          <h5 class="card-header-title">ویرایش محصول</h5>
          {% if object.is_published %}
          <a class="btn btn-sm btn-primary ms-2" href="{% url 'shop:product_detail' slug=object.slug %}">نمایش محصول</i></a>
          {% endif %}
        </div>
        <!-- End Header -->

        <!-- Body -->
        <form action="." method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        <div class="card-body">
            <div class="row d-flex ">
              <div class="col-md-6 mb-3">
                <label for="id_title">نام محصول</label>
                {{form.title}}
              </div>
              <div class="col-md-6 mb-3">
                <label for="id_slug">slug محصول</label>
                {{form.slug}}
              </div>
              <div class="col-md-6 mb-3">
                <label >تعداد</label>
                {{form.stock}}
              </div>

              <div class="col-md-6 mb-3">
                <label >وضعیت</label>
                {{form.status}}
              </div>
              <div class="col-md-6 mb-3">
                <label >دسته بندی</label>
                {{form.category}}
              </div>
              <div class="col-md-4 mb-3">
                <label >قیمت</label>
                {{form.price}}
              </div>
              <div class="col-md-2 mb-3">
                <label >درصد تخفیف</label>
                {{form.discount_percent}}
              </div>

              <div class="col-md-12 mb-3">
                <label >توضیحات کوتاه</label>
                {{form.brief_description}}
              </div>

              <div class="col-md-12 mb-3">
                <label >توضیحات</label>
                {{form.description|safe}}
              </div>

              
              <div class="col-md-12 mb-3">
                <label for="validationValidFileInput1">تصویر محصول</label>
                {{form.image}}
              </div>
            </div>
        </div>
        <div class="card-footer">
            <div class=" d-flex pt-5 justify-content-end">
                <a href="{% url 'dashboard:admin:product-delete' pk=object.pk %}" class="btn btn-danger ms-3">حذف</a>
                <a class="btn btn-secondary ms-3" href="{% url 'dashboard:admin:product-list' %}">بازگشت</a>
                <button type="submit" class="btn btn-primary ms-3">ثبت تغییرات</button>
            </div>
        </form>
      </div>
      <div>
        <div class="card">
            <!-- Header -->
            <div class="card-header border-bottom d-flex justify-content-between align-items-center">
                <h5 class="card-header-title">ویرایش تصاویر بیشتر</h5>
            </div>
            <!-- End Header -->

            <!-- Body -->
            <form action="{% url 'dashboard:admin:product-add-image' pk=object.pk %}" method="post"
                enctype="multipart/form-data">

                {% csrf_token %}
                <div class="card-body">
                    <div class="row d-flex align-items-center">
                        <div class="col-md-9 mb-3 d-flex align-items-center">
                            <label>تصویر محصول</label>
                            <input type="file" name="file" id="id_file" class="form-control" multiple accept="image/png, image/jpg, image/jpeg">
                        </div>
                        <div class="col-md-3 mb-3">
                            <button class="btn btn-primary ms-3" type="submit">ثبت تصویر</button>
                        </div>
                    </div>
                </div>


            </form>

            <div class="card-body">
                <div class="row d-flex ">
                    {% for product_image in object.product_images.all %}
                    <div class="col-md-2">
                        <img class="img-fluid" style="width:100px; height:100px" src="{{product_image.file.url}}"
                            alt="Image Description">
                        <form action="{% url 'dashboard:admin:product-remove-image' pk=object.pk image_id=product_image.pk %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger btn-sm">حذف تصویر</button>
                        </form>
                    </div>
                    {% endfor %}


                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block extra_js %}
<script>
    document.addEventListener('DOMContentLoaded', function() {
        // Get the title and slug input elements
        const titleInput = document.getElementById('id_title');
        const slugInput = document.getElementById('id_slug');

        // Function to slugify the title input, supporting Persian characters
        function slugify(text) {
            // Normalize to remove accents and convert to lowercase
            let slugified = text
                .toString()
                .normalize('NFD')  // Normalize to remove diacritical marks (accents)
                .toLowerCase()     // Convert to lowercase
                .replace(/[^a-z0-9\s\u0600-\u06FF\-]/g, '')  // Allow Persian chars (Unicode range for Persian: \u0600-\u06FF)
                .replace(/\s+/g, '-')    // Replace spaces with hyphens
                .replace(/-+/g, '-');    // Replace multiple hyphens with one

            // Return the slug directly (without URL encoding)
            return slugified;
        }

        // Add an event listener to the title input
        titleInput.addEventListener('input', function() {
            // Update the slug field with the slugified version of the title
            slugInput.value = slugify(titleInput.value);
        });
    });

    document.getElementById('id_image').addEventListener('change', function(event) {
        var reader = new FileReader();
        var file = event.target.files[0];

        if (file) {
            // When a file is selected, show the preview
            reader.onload = function(e) {
                var imagePreview = document.getElementById('imagePreview');
                var imagePreviewContainer = document.getElementById('imagePreviewContainer');
                
                // Set the src attribute of the img tag to the file data
                imagePreview.src = e.target.result;

                // Show the preview container
                imagePreviewContainer.style.display = 'block';
            };

            // Read the file as a data URL
            reader.readAsDataURL(file);
        }
    });

</script>
{% endblock extra_js %}