core/cart/urls.py
from django.urls import path, re_path
from . import views

app_name = "cart"

urlpatterns = [
    path("session/add-product", views.SessionAddProductView.as_view(), name="session-add-product"),
    path("session/remove-product", views.SessionRemoveProductView.as_view(), name="session-remove-product"),
    path("session/update-product-quantity", views.SessionUpdateProductQuantityView.as_view(), name="session-update-product-quantity"),
    path("summary", views.SessionCartSummaryView.as_view(), name="cart-summary"),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("website.urls")),
    path('dashboard/', include("dashboard.urls")),
    path('accounts/', include("accounts.urls")),
    path('shop/', include("shop.urls")),
    path('cart/', include("cart.urls")),
    path('order/', include("order.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

if settings.SHOW_DEBUGGER_TOOLBAR:
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls')),
                    ]

core/order/urls.py
from django.urls import path
from . import views

app_name = "order"

urlpatterns = [
    path("checkout/", views.OrderCheckoutView.as_view(), name="checkout"),
]

core/order/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
# Create your models here.

class OrderStatusType(models.IntegerChoices):
    pending = 1, "در انتظار پرداخت"
    processing = 2, "در حال پردازش"
    shipping = 3, "ارسال شده"
    delivered = 4, "تحویل داده شده"
    canceled = 5, "لغو شده"
    
class UserAddressModel(models.Model):
    user = models.ForeignKey("accounts.User", on_delete=models.CASCADE)
    
    address = models.CharField(max_length=250)
    state = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    zip_code = models.CharField(max_length=50)
    
    
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

class CouponModel(models.Model):
    code = models.CharField(max_length=100)
    discount_percent = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(100)])
    max_limit_usage = models.PositiveIntegerField(default=10)
    used_by = models.ManyToManyField("accounts.User", related_name="coupon_users")
    
    expiration_date = models.DateTimeField(null=True, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

class OrderModel(models.Model):
    user = models.ForeignKey('accounts.User', on_delete=models.PROTECT)
    
    address = models.CharField(max_length=250)
    state = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    zip_code = models.CharField(max_length=50)
    
    status = models.IntegerField(choices=OrderStatusType.choices, default=OrderStatusType.pending.value)
    total_price = models.DecimalField(max_digits=10, decimal_places=0)
    coupon = models.ForeignKey(CouponModel, on_delete=models.PROTECT, null=True, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    
    
class OrderItemModel(models.Model):
    order = models.ForeignKey(OrderModel, on_delete=models.CASCADE)
    product = models.ForeignKey("shop.ProductModel", on_delete=models.PROTECT)
    
    quantity = models.PositiveIntegerField(default=0)
    price = models.DecimalField(max_digits=10, decimal_places=0)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"{self.product.title} - {self.cart.id}"

core/order/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from order.permissions import HasCustomerAccessPermission
# Create your views here.


class OrderCheckoutView(LoginRequiredMixin, HasCustomerAccessPermission, TemplateView):
    template_name = "order/checkout.html"

core/templates/order/checkout.html
{% extends "base.html" %}
{% load static %}


{% block content %}
    <!-- Content -->
    <div class="container content-space-1 content-space-lg-2">
        <div class="row">
          <div class="col-lg-8 mb-7 mb-lg-0">
            <h4 class="mb-3">انتخاب آدرس </h4>
  
            <!-- Form -->
            <form class="needs-validation" novalidate>
  
  
              <hr class="my-4">
  
              <div class="d-grid gap-2">
  
                <!-- Check -->
                <div class="form-check">
                  <input type="radio" class="form-check-input" name="address" id="address-1" checked
                  required >
                  <label class="form-check-label" for="address"> کرج، xxxx ، بلوار xxx ، خیابان xxx ، بلوک xxx</label>
                </div>
                <div class="form-check">
                  <input type="radio" class="form-check-input" name="address" id="address-2" required>
                  <label class="form-check-label" for="address-2"> کرج، xxxx ، بلوار xxx ، خیابان xxx ، بلوک xxx</label>
                </div>
                <!-- End Check -->
                <div>
                  <a class="" href="./account-address.html">مدیریت آدرس ها</a>
                </div>
              </div>
  
              <hr class="my-4">
  
              <h4 class="mb-3">روش پرداخت</h4>
  
              <div class="my-3">
                <!-- Check -->
                <div class="form-check">
                  <input id="creditShopCheckout" name="paymentMethod" type="radio" class="form-check-input" checked
                    required>
                  <label class="form-check-label" for="creditShopCheckout">پرداخت آنلاین</label>
                </div>
                <!-- End Check -->
  
                <!-- Check -->
                <div class="form-check">
                  <input id="debitShopCheckout" name="paymentMethod" type="radio" class="form-check-input" required>
                  <label class="form-check-label" for="debitShopCheckout">کارت به کارت</label>
                </div>
                <!-- End Check -->
              </div>
  
  
              <hr class="my-4">
  
              <div class="row align-items-center">
  
  
  
                <div class="col-sm text-center text-sm-start">
                  <a class="link" href="{% url 'cart:cart-summary' %}">
                    <i class="bi-chevron-left small ms-1"></i> بازگشت به سبد خرید
                  </a>
                </div>
                <!-- End Col -->
              </div>
              <!-- End Row -->
            </form>
            <!-- End Form -->
          </div>
          <!-- End Col -->
  
          <div class="col-lg-4">
            <div class="ps-lg-4">
              <!-- Card -->
              <div class="card card-sm shadow-sm mb-4">
                <div class="card-body">
                  <div class="border-bottom pb-4 mb-4">
                    <h3 class="card-header-title">خلاصه سفارش</h3>
                  </div>
  
                  <form>
  
                    <div class="input-group border-bottom pb-4 mb-3 ">
                      <input type="text" class="form-control text-center" name="name" placeholder="کد تخفیف"
                      aria-label="کد تخفیف">
                      <button class="btn btn-primary"> بررسی</button>
                    </div>
  
                    <div class="border-bottom pb-4 mb-4">
                      <div class="d-grid gap-3">
  
                        <!-- End Row -->
  
                        <dl class="row">
                          <dt class="col-sm-6">هزینه ارسال</dt>
                          <dd class="col-sm-12 text-sm-end mb-0">برای تهران و حومه 35000 تومان</dd>
                          <dd class="col-sm-12 text-sm-end mb-0">برای شهرستان ها 50000 تومان</dd>
                        </dl>
                        <!-- End Row -->
                      </div>
                    </div>
  
                    <div class="d-grid gap-3 mb-4">
                      <dl class="row">
                        <dt class="col-sm-6">مالیات تخمینی</dt>
                        <dd class="col-sm-12 text-sm-end mb-0">با ضریب 9% - 35000 تومان</dd>
  
                      </dl>
                      <!-- End Row -->
  
                      <dl class="row">
                        <dt class="col-sm-6">جمع کل</dt>
                        <dd class="col-sm-6 text-sm-end mb-0">450000 تومان</dd>
                      </dl>
                      <!-- End Row -->
                    </div>
  
                    <div class="d-grid">
                      <a class="btn btn-primary btn-lg" href="/order-completed.html">ثبت نهایی</a>
                    </div>
                  </form>
                </div>
                <!-- End Card -->
              </div>
  
              <!-- Media -->
              <div class="d-flex align-items-center">
                <div class="flex-shrink-0">
                  <div class="svg-icon svg-icon-sm text-primary">
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                      <path fill-rule="evenodd" clip-rule="evenodd"
                        d="M22.1671 18.1421C22.4827 18.4577 23.0222 18.2331 23.0206 17.7868L23.0039 13.1053V5.52632C23.0039 4.13107 21.8729 3 20.4776 3H8.68815C7.2929 3 6.16183 4.13107 6.16183 5.52632V9H13C14.6568 9 16 10.3431 16 12V15.6316H19.6565L22.1671 18.1421Z"
                        fill="#035A4B" />
                      <path opacity="0.3" fill-rule="evenodd" clip-rule="evenodd"
                        d="M1.98508 18V13C1.98508 11.8954 2.88051 11 3.98508 11H11.9851C13.0896 11 13.9851 11.8954 13.9851 13V18C13.9851 19.1046 13.0896 20 11.9851 20H4.10081L2.85695 21.1905C2.53895 21.4949 2.01123 21.2695 2.01123 20.8293V18.3243C1.99402 18.2187 1.98508 18.1104 1.98508 18ZM5.99999 14.5C5.99999 14.2239 6.22385 14 6.49999 14H11.5C11.7761 14 12 14.2239 12 14.5C12 14.7761 11.7761 15 11.5 15H6.49999C6.22385 15 5.99999 14.7761 5.99999 14.5ZM9.49999 16C9.22385 16 8.99999 16.2239 8.99999 16.5C8.99999 16.7761 9.22385 17 9.49999 17H11.5C11.7761 17 12 16.7761 12 16.5C12 16.2239 11.7761 16 11.5 16H9.49999Z"
                        fill="#035A4B" />
                    </svg>
  
                  </div>
                </div>
                <div class="flex-grow-1 ms-2">
                  <span class="small me-1">نیاز به پشتیبانی دارید؟</span>
                  <a class="link small" href="#">ارسال تیکت</a>
                </div>
              </div>
              <!-- End Media -->
            </div>
          </div>
          <!-- End Col -->
        </div>
        <!-- End Row -->
      </div>
      <!-- End Content -->

{% endblock content %}